name: Build and Deploy

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

env:
  TEST_VAR: "test value"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: sjohnr/spring-gradle-build-action@v1
        with:
          task: 'printEnv'