name: CI

on:
  push:
    branches: [ main ]
#    tags: [ .* ]
#  pull_request:
#    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: extract-version
        name: Extract version
        run: |
          version=$(cat gradle.properties | grep "version=" | awk -F'=' '{print $2}')
          echo "Setting version=$version"
          echo "project_version=$version" >> $GITHUB_ENV
#          if [[ "$version" != *"-SNAPSHOT"* ]]
#          then
#          fi
      - name: perform-release
        if: ${{ !endsWith(env.project_version, '-SNAPSHOT') }}
        run: |
          version=${{ env.project_version }}
          echo "Version $version is a release version."
