name: CI

on:
  push:
    branches: [ main ]
#    tags: [ .* ]
#  pull_request:
#    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: extract-version
        name: Extract version
        run: |
          version=$(cat gradle.properties | grep "version=" | awk -F'=' '{print $2}')
          echo "Setting env.project_version=$version"
          echo "project_version=$version" >> $GITHUB_ENV
      - id: set-perform-release
        name: Set perform release flag
        if: ${{ !endsWith(env.project_version, '-SNAPSHOT') }}
        run: |
          echo "Setting env.perform_release=true"
          echo "perform_release=true" >> $GITHUB_ENV
      - id: perform-release
        name: Perform release
        if: ${{ env.perform_release }}
        run: |
          repo=${{ github.repository }}
          branch=${{ github.ref_name }}
          version=${{ env.project_version }}
          access_token=${{ secrets.GH_ACTIONS_REPO_TOKEN }}
          echo "Performing release of $repo/$version."
          until curl -f -s https://repo1.maven.org/maven2/org/springframework/security/spring-security-core/$version/ > /dev/null
          do
            sleep 30
            echo "."
          done
          echo "Artifacts for $repo/$version have been released to Maven Central."
          echo "Tagging and publishing $repo/$version release to GitHub."
          echo "./gradlew createGitHubRelease -PnextVersion=$version -Pbranch=$branch -PcreateRelease=true -PgitHubAccessToken=$access_token"
