name: CI

on:
  push:
    branches: [ main ]
#    tags: [ .* ]
#  pull_request:
#    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: extract-version
        name: Extract version
        run: |
          version=$(cat gradle.properties | grep "version=" | awk -F'=' '{print $2}')
          echo "::debug::Setting version=$version"
          echo "::set-output name=version::$version"
#          if [[ "$version" != *"-SNAPSHOT"* ]]
#          then
#          fi
      - name: perform-release
        if: ${{ !endsWith(steps.extract-version.outputs.version, '-SNAPSHOT') }}
        run: |
          version=${{ steps.extract-version.outputs.version }}
          echo "Version $version is a release version."
