name: CI

on:
  push:
    branches: [ main ]
#    tags: [ .* ]
#  pull_request:
#    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: perform-release
        run: |
          version=$(cat gradle.properties | grep "version=" | awk -F'=' '{print $2}')
          if [[ "$version" != *"-"* ]]
          then
            echo "Version $version is a release version."
            // wait for done
          else
            echo "Version $version is not a release version."
          fi
