name: Notification test

on:
#  push:
#    branches:
#      - 'main'
  workflow_dispatch:

jobs:
  notify_result:
    name: Test Slack App
    runs-on: ubuntu-latest
    steps:
      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.19.0
        with:
          # channel: '#spring-security-team'
          channel-id: 'G9B4T6XHN'
          slack-message: 'spring-security-announcing `0.0.0` is available (this is a test)'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
