name: Notification test

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  test_step:
    name: 'Test step'
    runs-on: ubuntu-latest
    steps:
      - run: echo "Test" && exit 1
  notify:
    name: Check for failures
    runs-on: ubuntu-latest
    needs: [test_step]
    if: failure()
    steps:
      - name: Send notification
        run: |
          echo "Failed: ${{ github.actor }}'s ${{ github.event_name}} on ${{ github.ref_name }}\nWorkflow: ${{ github.workflow }} <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|#${{ github.run_number }}> completed in ..."
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'
