name: Release

on:
  schedule:
    - cron: '45 16 * * MON'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: perform-release
        run: |
          date
          if [ "$((($(date +%e) - 1) / 7 + 1))" = "3" ] && [ "$(date +%A)" = "Monday" ]
          then
            echo "It is the third Monday of the month."
          fi
