name: Release

on:
  schedule:
    - cron: '45 16 * * MON'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: perform-release
        run: |
          if [ "$((($(date +%e) - 1) / 7 + 1))" = "3" ] && [ "$(date +%A)" = "Friday" ]
          then
            echo "It is the third Friday of the month."
            version=$(cat gradle.properties | grep "version=" | awk -F'=' '{print $2}')
            if [[ "$version" != *"-"* ]]
            then
              echo "Version $version is a release version."
              // wait for done
            else
              echo "Version $version is not a release version."
            fi
          fi
