name: Wait For Done

on:
  schedule:
    - cron: '45 23 * * THU'
  workflow_dispatch:

jobs:
  upload-version:
    name: Upload version.txt
    runs-on: ubuntu-latest
    steps:
#      - uses: actions/checkout@v2
      - name: Write version.txt
        run: |
          echo "5.7.0" > version.txt
      - name: Upload version.txt
        uses: actions/upload-artifact@v2
        with:
          name: version
          path: version.txt

  check-release:
    name: Check release
    needs: upload-version
    runs-on: ubuntu-latest
    steps:
#      - uses: actions/checkout@v2
      - name: Download version.txt
        uses: actions/download-artifact@v2
        with:
          name: version
      - name: Check version.txt
        run: |
          version=$(cat version.txt)
          if [[ "$version" != *"-"* ]]
          then
            echo "Version $version is a release version."
            until curl -f -s --show-error https://repo1.maven.org/maven2/org/springframework/security/spring-security-core/$version/ > /dev/null
            do
              sleep 10
              echo "."
            done
            echo "Finished"
          fi
#      - name: Uptime Action
#        uses: srt32/uptime@v0.2.1
#        with:
#          url-to-hit: "https://example.com"
#          expected-statuses: "200,301"
      - name: Write version.txt again
        run: |
          echo "5.7.1-SNAPSHOT" > version.txt
      - name: Upload version.txt
        uses: actions/upload-artifact@v2
        with:
          name: version
          path: version.txt

  check-pre-release:
    name: Check pre-release
    needs: check-release
    runs-on: ubuntu-latest
    steps:
#      - uses: actions/checkout@v2
      - name: Download version.txt
        uses: actions/download-artifact@v2
        with:
          name: version
      - name: Check version.txt
        run: |
          version=$(cat version.txt)
          if [[ "$version" == *"-"* ]]
          then
            echo "Version $version is a pre-release version."
          else
            echo "Version $version is not a pre-release version."
          fi
